# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hTWOo UI
email: stefan.bauer@n8d.at
description: # this means to ignore newlines until "baseurl:"
  Fluent Design made easy with hTWOo UI. Suitable for every Microsoft 365 customisation
baseurl: "/htwoo" # the subpath of your site, e.g. /blog
url: "https://lab.n8d.studio" # the base hostname & protocol for your site
twitter_username: htwooui
github_username:  stfbauer

# Build settings
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

features:
  - components: false

sections:
  - title: Getting Started
    url: getting-started
    type: static
  - title: About hTWOo
    url: about
    type: static
  - title: Components & Style Guide
    url: /htwoo/htwoo-core/index.html
    type: static
    permlink: true
  - title: hTWOo - Core
    url: /htwoo/htwoo-core/index.html
    type: static
    permlink: true
  - title: hTWOo - React
    url: /htwoo/htwoo-react/
    type: static
    permlink: true
  - title: hTWOo - Icons
    url: https://my.n8d.at/htwoo-icons
    type: static
    permlink: true
  - title:  How To
    path: how-to
    group: how-to
    type: dynamic
  - title: Support
    type: static
    url: support
  - title: Code of Conduct
    type: static
    url: CODE_OF_CONDUCT
  - title: Engage on GitHub
    type: static
    url: https://github.com/n8design/htwoo
    permlink: true
  - title: Contribute
    type: static
    url: contribute

# Google services
#google_analytics: G-7GBZFB89Y7

social-network-links:
  github: n8design
  twitter: htwooui

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false